/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Controller: typeof import('./src/components/TV-AirContditor/controller.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    TvButton: typeof import('./src/components/tvButton.vue')['default']
  }
}
